version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    volumes:
      - ./work_app:/usr/src/app
    ports:
      - "8000:8000"
